[features]
seeds = false
skip-lint = false
[programs.localnet]
sigverify_example = "seHtQtXsNYkE6qd8C197kbjmovMU8bVA22kRELQ4NNZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/bare/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
